### ISSUE TITLE
Pass kubeconfig path directly

### ISSUE THREAD

**Issue by iosifnicolae2** [magnolia-sre/terraform-kubernetes-kubectl-cmd#1]
Hi.

It would awesome to add an input variable named kubeconfig_path.

Right now, I'm using [this](https://github.com/LuxChanLu/terraform-kubernetes-kubectl-cmd) fork by passing the following variables:
```
  endpoint = yamldecode(file(var.kubeconfig_path))["clusters"][0]["cluster"]["server"]
  token = null
  ca-certificate = yamldecode(file(var.kubeconfig_path))["clusters"][0]["cluster"]["certificate-authority-data"]
  client-certificate = yamldecode(file(var.kubeconfig_path))["clusters"][0]["cluster"]["client-certificate-data"]
  client-key = yamldecode(file(var.kubeconfig_path))["users"][0]["user"]["client-key-data"]
```

It would be great to have all the 3 authentication methods in one terraform module.

Thank you!

**Comment by iosifnicolae2** [comment]
cc @LuxChanLu

**Comment by aseixas-mgnl** [comment]
I've released this newer version with support for both, @iosifnicolae2 can you check that it works on your side ? (if not, feel free to tag me and add any console output). Thanks! https://github.com/magnolia-sre/terraform-kubernetes-kubectl-cmd/releases/tag/v1.2.1

**Comment by aseixas-mgnl** [comment]
Closed for inactivity
