### ISSUE TITLE
Running kubectl command whilst using plugins does not work

### ISSUE THREAD

**Issue by vjkancherla** [magnolia-sre/terraform-kubernetes-kubectl-cmd#3]
Good evening, 

I am trying to run the following kubectl command, whilst using the "aws-auth" plugin, and it fails:

```
kubectl aws-auth upsert --maproles --rolearn arn:aws:iam::xxxxxxx:role/xxx-test-env-iam-role --username '{{SessionName}}' --groups system:masters --append
```

The error is:

```
Error running command 'kubectl --kubeconfig <(echo $KUBECONFIG | base64 -d) aws-auth upsert --maproles --rolearn
│ arn:aws:iam::xxxxxx:role/xxx-test-env-iam-role--username '{{SessionName}}' --groups
│ system:masters --append >> cmd-jenkins.log-0': exit status 1. Output: Error: flags cannot be placed before plugin
│ name: --kubeconfig
```

**Comment by dohoangkhiem** [comment]
It seems because any options placed before kubectl plugin name would result in error  https://github.com/kubernetes/kubectl/issues/884 ... We will provide fix asap

**Comment by dohoangkhiem** [comment]
The issue is fixed and pushed in https://github.com/magnolia-sre/terraform-kubernetes-kubectl-cmd/commit/04128bd9b6d9f92c0b4c1edb1de51daf0cca76da, thanks a lot for reporting @vjkancherla !
